### ISSUE TITLE
卒業制作[4] issueベースの開発

### ISSUE THREAD

**Issue by masashi2610** [masashi2610/runteq_graduation_work#19]
■Webアプリの概要
野球のスパイクに特化したサービスで、スパイクの管理・検索ができます
MVP:自分のスパイクを登録し、自分のスパイク遍歴が作れる
本リリース：新しいスパイクを購入するときに、おすすめスパイクが検索できる

■1週間辺りの開発に向けられる時間
- 1週間あたり：10時間

■ProjectsのURL
https://github.com/users/masashi2610/projects/1

■MVPリリースまで
- [ ] 環境構築
- [ ] トップページ
- [ ] ヘッダー
- [ ] 新規登録ページ
- [ ] ログイン/ログアウトページ
- [ ] パスワード確認ページ
- [ ] パスワード変更ページ
- [ ] マイページ
- [ ] スパイク登録ページ
- [ ] スパイク編集機能
- [ ] スパイク削除機能

■MVP後
- [ ] スパイク検索ページ
- [ ] スパイクオススメ詳細ページ
- [ ] フッター
- [ ] お問い合わせ
- [ ] 利用規約

■MVPレビュー依頼予定日
予定日：2024年 11月 30日

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

**Comment by ippei-shimizu** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- フッター
- お問い合わせページ
- 利用規約ページ

**Comment by masashi2610** [comment]
コメント、ありがとうございます

アドバイスいただいた通り、下記3点はMVPからは外そうと思います

- フッター
- お問い合わせページ
- 利用規約ページ
